---
title: "Quarto Practice"
author: "Melannie Moreno Rolon"
format: html
editor: visual
execute: 
  warning: false
---

Suppressing warnings and messages for one code chunk:

```{r}
#| warning: false
#| message: false
library(tidyverse)
```

Running code, but not showing code or output:

```{r}
#| include: false
head(starwars) #return first 6 lines of star wars data

dim(starwars) #dimensions of star wars data
```

Showing output, but not code:

```{r}
#| warning: false
#| echo: false
ggplot(data = starwars, aes(x = height, y = mass, color = mass)) +
  geom_point() +
  labs(x = "Height (cm)",
       y = "Mass (kg)")
```

Show only code and output:

```{r}
#| warning: false
#| fig-cap: "caption text"
ggplot(data = starwars, aes(x = height)) + 
  geom_histogram(color = "red", fill = "blue")
```

Find summary stats for Star Wars characters

```{r}
sw_height_mean <- mean(starwars$height, na.rm = TRUE)
sw_height_median <- median(starwars$height, na.rm = TRUE)
sw_height_var <- var(starwars$height, na.rm = TRUE)
sw_height_sd <- sd(starwars$height, na.rm = TRUE)
```

The mean height of the characters in Star Wars is `r round(sw_height_mean, 1)` centimeters.  



